### ISSUE TITLE
Error running "catalyst ingest"

### ISSUE THREAD

**Issue by yeshymanoharan** [enigmampc/catalyst-docs#11]
When I try to run "catalyst ingest" to download all of the files, I get hit with the error "No bundle registered with the name None".

<img width="492" alt="screen shot 2017-10-27 at 8 30 55 pm" src="https://user-images.githubusercontent.com/11007399/32129491-d55e453c-bb55-11e7-885e-6956a3eb6d0a.png">

I am using virtualenv and pip installed enigma-catalyst

**Comment by lacabra** [comment]
As the homepage on this wiki says, some of the documentation on this site is out of date, and that's the case for the command that you report. Instead, use `catalyst ingest-exchange -x {exchange_name}` and refer to https://enigmampc.github.io/catalyst/beginner-tutorial.html for up to date documentation. 
Best,
Victor
