### ISSUE TITLE
Ubuntu 14.04 install fails with error about prereleases

### ISSUE THREAD

**Issue by js7558** [enigmampc/catalyst-docs#4]
Following instructions on https://enigma.co/catalyst/#/getstarted/installation on Ubuntu 14.04.5 LTS.   Instruction #3 

pip install enigma-catalyst 

results in error 

(catalyst-venv)jason@mouse:~/catalyst-venv/bin$ pip install  enigma-catalyst     
Downloading/unpacking enigma-catalyst
  Could not find a version that satisfies the requirement enigma-catalyst (from versions: 0.1.dev9, 0.2.dev2, 0.1.dev4, 0.1.dev5, 0.1.dev3, 0.2.dev1, 0.1.dev8, 0.1.dev6)
Cleaning up...
No distributions matching the version for enigma-catalyst
Storing debug log for failure in /tmp/tmpYSRuZa

Workaround is to run pip install with --pre switch.    

(catalyst-venv)jason@mouse:~/catalyst-venv/bin$ pip install --pre enigma-catalyst
Downloading/unpacking enigma-catalyst
  Downloading enigma-catalyst-0.2.dev2.tar.gz (687kB): 687kB downloaded
  Running setup.py (path:/home/jason/catalyst-venv/build/enigma-catalyst/setup.py) egg_info for package enigma-catalyst
....

More errors results after this, will submit additional reports.

**Comment by lacabra** [comment]
Thank you for reporting this. This has been documented in a revamped page on Troubleshooting at https://github.com/enigmampc/catalyst-docs/wiki/Troubleshooting-Installation
