### ISSUE TITLE
Ubuntu 14.04 install fails with find_packages error

### ISSUE THREAD

**Issue by js7558** [enigmampc/catalyst-docs#5]
Following instructions on https://enigma.co/catalyst/#/getstarted/installation ... Worked around prerelease issue with --pre switch to pip install.   Now produces error:

------------------------------------------------------
(catalyst-venv)jason@mouse:~/catalyst-venv/bin$ pip install --pre enigma-catalyst
Installing collected packages: enigma-catalyst
  Running setup.py install for enigma-catalyst
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jason/catalyst-venv/build/enigma-catalyst/setup.py", line 298, in <module>
        packages=find_packages(include=["catalyst", "catalyst.*"]),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    Complete output from command /home/jason/catalyst-venv/bin/python -c "import setuptools, tokenize;__file__='/home/jason/catalyst-venv/build/enigma-catalyst/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2tMmIh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jason/catalyst-venv/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/jason/catalyst-venv/build/enigma-catalyst/setup.py", line 298, in <module>

    packages=find_packages(include=["catalyst", "catalyst.*"]),

TypeError: find_packages() got an unexpected keyword argument 'include'
.....................
------------------------------------------------------

This appears to result from an out of date version of setuptools.   Work around is to update setup tools with command 
pip install -U setuptools

---------------------------------------------
(catalyst-venv)jason@mouse:~/catalyst-venv/bin$ pip install -U setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/1b/95/e6f28144fdb6c06186c1f0e70cea02791e6ec787682bdfc437ce69b8186c/setuptools-36.4.0-py2.py3-none-any.whl#md5=cd2f7498abadf0ef7aff9f9297cae33d
  Downloading setuptools-36.4.0-py2.py3-none-any.whl (478kB): 478kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed setuptools
Cleaning up...
(catalyst-venv)jason@mouse:~/catalyst-venv/bin$ pip2.7 install --pre enigma-catalyst                         
Downloading/unpacking enigma-catalyst
  Downloading enigma-catalyst-0.2.dev2.tar.gz (687kB): 687kB downloaded
---------------------------------------------

This gets me further than I got before but I am now seeing another error related to Python.h.  I'll post another issue once I get past that.

**Comment by lacabra** [comment]
Thank you for reporting this issue. This is a known issue and was already documented on our Troubleshooting Installation page at https://github.com/enigmampc/catalyst-docs/wiki/Troubleshooting-Installation.
This issue has been addressed more permanently with commit 7f602d7fcc1015ab6d366884b1d2c931493a06df that specifies a more up to date version of setuptools in the requirements file, and will be included in the next release.
