### ISSUE TITLE
Ubuntu 14.04 install fails with Python.h error

### ISSUE THREAD

**Issue by js7558** [enigmampc/catalyst-docs#6]
following instructions at https://enigma.co/catalyst/#/getstarted/installation  .   Worked around problems with prerelease and find_packages (submitted different issues for these).   Installation fails with compile error related to Python.h

----------------------------------------------------------------
root@mouse:~# pip install --pre enigma-catalyst
Downloading/unpacking enigma-catalyst
  Downloading enigma-catalyst-0.2.dev2.tar.gz (687kB): 687kB downloaded
  Running setup.py (path:/tmp/pip_build_root/enigma-catalyst/setup.py) egg_info for package enigma-catalyst
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-88hkUx/Cython-0.26.1/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/enigma-catalyst/setup.py", line 322, in <module>
        **conditional_arguments
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1028, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.

warning: no files found matching 'Doc/*'

warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'

warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'

warning: no files found matching '*.pxd' under directory 'Cython/Utility'

/tmp/easy_install-88hkUx/Cython-0.26.1/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

compilation terminated.

--------------------------------------------------

The problem here is that python-dev is missing.   Maybe should be included in virtualenv or added as an installation prerequisite?   Installation of python-dev adds Python.h and resolves the issue:

---------------------------------------------------------
(catalyst-venv)jason@mouse:~/catalyst-venv/bin$ sudo apt-get install python-dev
     <<output is attached as a file, significant numbers of compiler warnings, fortran errors, and other messaging>>  

Looks like the install ultimately failed after like 40 minutes of running due to some sort of Unicode Decode Error :-( ... 
[enigma-catalyst.txt](https://github.com/enigmampc/catalyst-docs/files/1297567/enigma-catalyst.txt)

**Comment by abnera** [comment]
This should fix it and is independent of the virtual environment since it's from the apt-get files.
- `sudo apt-get install python-dev`

**Comment by lacabra** [comment]
Thanks for reporting this issue. It has been documented on our Troubleshooting Guide on our wiki https://github.com/enigmampc/catalyst-docs/wiki/Troubleshooting-Installation

python-dev is not available through pip, so we can't include it in the requirements.txt. Given that our preferred installation method now is through Conda and is well documented, I am closing this issue (this issue is still documented on our Troubleshooting Install page for future reference).
